# -*- coding: utf-8 -*-
"""BD_Credit_2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eO-ammdAs_w19c5wAo2BpZQenWtdFiHn

# **BD MICROCREDITOS 2025**

Se tienen una base de microcreditos en el 2025 para clientes naturales.

**Proyecto Fase 1:** Seleccionar dataset personal, limpieza básica en Pandas, modularizar limpieza en funciones puras (archivo .py separado).
"""

import pandas as pd

def cargar_datos(ruta: str) -> pd.DataFrame:
    return pd.read_excel(ruta)

def normalizar_columnas(df: pd.DataFrame) -> pd.DataFrame:
    df.columns = df.columns.str.lower()
    return df

def convertir_fecha(df: pd.DataFrame) -> pd.DataFrame:
    df["loandate"] = pd.to_datetime(df["loandate"])
    return df

def eliminar_nulos(df: pd.DataFrame) -> pd.DataFrame:
    return df.dropna()

def eliminar_duplicados(df: pd.DataFrame) -> pd.DataFrame:
    return df.drop_duplicates()

def crear_ratio_aprobacion(df: pd.DataFrame) -> pd.DataFrame:
    df["ratio_aprobacion"] = df["cupo_aprobado"] / df["cupo_solicitado"]
    return df

def ejecutar_pipeline() -> None:
    df = cargar_datos("/content/BD_Credit_2025_completo.xlsx")
    df = normalizar_columnas(df)
    df = convertir_fecha(df)
    df = eliminar_nulos(df)
    df = eliminar_duplicados(df)
    df = crear_ratio_aprobacion(df)

    print(df.head())
    print("Dimensión final:", df.shape)

if __name__ == "__main__":
    ejecutar_pipeline()

pip install pydantic

"""# **Crear esquemas Pydantic para el dataset elegido en Fase 1 (InputSchema y OutputSchema).**"""

from pydantic import BaseModel, Field
from datetime import datetime


class CreditInputSchema(BaseModel):
    customer_id: int = Field(..., example=1082423)
    loandate: datetime = Field(..., example="2020-05-28")
    age: float = Field(..., gt=18, example=35)
    income: float = Field(..., gt=0, example=1500)
    time_experience: float = Field(..., ge=0, example=5)
    cupo_solicitado: float = Field(..., gt=0, example=20000)
    score_1: int = Field(..., ge=0, le=1000)
    score_2: int = Field(..., ge=0, le=1000)
    score_3: int = Field(..., ge=0, le=1000)
    score_4: int = Field(..., ge=0, le=1000)


class CreditOutputSchema(BaseModel):
    customer_id: int
    cupo_solicitado: float
    cupo_aprobado: float
    ratio_aprobacion: float
    resultado_cobranza: str

from pydantic import BaseModel, Field
from datetime import datetime


class CreditInputSchema(BaseModel):
    customer_id: int = Field(..., example=1082423)
    loandate: datetime = Field(..., example="2020-05-28")
    age: float = Field(..., gt=18, example=35)
    income: float = Field(..., gt=0, example=1500)
    time_experience: float = Field(..., ge=0, example=5)
    cupo_solicitado: float = Field(..., gt=0, example=20000)
    score_1: int = Field(..., ge=0, le=1000)
    score_2: int = Field(..., ge=0, le=1000)
    score_3: int = Field(..., ge=0, le=1000)
    score_4: int = Field(..., ge=0, le=1000)

data = {
    "customer_id": 1082423,
    "loandate": "2020-05-28",
    "age": 30,
    "income": 2000,
    "time_experience": 5,
    "cupo_solicitado": 15000,
    "score_1": 500,
    "score_2": 600,
    "score_3": 650,
    "score_4": 700
}

credit = CreditInputSchema(**data)
print(credit)